INSERT INTO `feedback` (`feedback_id`,`comment`,`event_id`,`user_id`) VALUES (51,'The Global Business Leaders Conference was a game-changing experience, offering invaluable insights from industry leaders and fostering global collaboration.',41,1);
INSERT INTO `feedback` (`feedback_id`,`comment`,`event_id`,`user_id`) VALUES (52,'The Global Business Leaders Conference provided a solid platform for networking and discussion, though some sessions felt too focused on theoretical concepts rather than actionable strategies.',41,34);
INSERT INTO `feedback` (`feedback_id`,`comment`,`event_id`,`user_id`) VALUES (53,'Unfortunately, the Global Business Leaders Conference fell short of expectations, with many sessions lacking depth and offering little more than surface-level content.',41,40);
INSERT INTO `feedback` (`feedback_id`,`comment`,`event_id`,`user_id`) VALUES (54,'The Food and Wine Festival was an unforgettable experience, showcasing delicious cuisine and exceptional wines in an atmosphere that celebrated gourmet culture.',54,34);
INSERT INTO `feedback` (`feedback_id`,`comment`,`event_id`,`user_id`) VALUES (55,'The Food and Wine Festival had some great food and wine options, but the long lines and crowded venue made it a bit challenging to fully enjoy the event.',54,40);
INSERT INTO `feedback` (`feedback_id`,`comment`,`event_id`,`user_id`) VALUES (56,'I was disappointed with the Food and Wine Festival, as many of the wine offerings were underwhelming, and the food selections didn’t live up to the hype.',54,1);
INSERT INTO `feedback` (`feedback_id`,`comment`,`event_id`,`user_id`) VALUES (61,'The Rock \'n\' Roll Concert was absolutely electrifying, with high-energy performances that had the crowd on their feet from start to finish!',52,1);
INSERT INTO `feedback` (`feedback_id`,`comment`,`event_id`,`user_id`) VALUES (62,'The Rock \'n\' Roll Concert had some good moments, but the sound quality could have been better, and certain acts felt a bit off compared to the hype',52,34);
INSERT INTO `feedback` (`feedback_id`,`comment`,`event_id`,`user_id`) VALUES (63,'I was underwhelmed by the Rock \'n\' Roll Concert, as it lacked the expected energy, and the setlist didn’t resonate with the crowd the way it should have.',52,40);
